---
title: "Получение сведений о системе"
author: Tyvan Maxim BISO-02-20
format:
    md:
        output-file: README.md
engine: knitr
---

## Цель работы

Получить сведения об используемой системе

## Исходные данные

1. Ноутбук Huawei

2. ОС Ubuntu, запущенная в среде WSL (Windows Subsystem for Linux)

3. Интерпретатор командной оболочки bash 5.2.15

## План

1. Ввод команд в эмулятор терминала

2. Анализ данных

## Ход работы

1. Для начала получим сведения об используемом дистрибутиве:

```bash
golubgleb@Regius2:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

В результате выполнения данной команды было определён используемый дистрибутив - Ubuntu 22.04 LTS

2. Затем получим сведения о версии ядра:

```bash
golubgleb@Regius2:~$ uname -a
Linux Regius2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

В результате выполнения данной команды была получена версия ядра - 5.15.90.1, дата компиляции ядра - 27 января 2023 года.

3. Далее можно получить сведения о процессоре:

```bash
golubgleb@Regius2:~$ cat /proc/cpuinfo | grep "model name"
model name      : 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
model name      : 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
model name      : 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
model name      : 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
```

Было определено, что используемый процессор - четырёхпоточный Intel Core i3-1115G4 с тактовой частотой 3.0 ГГц.

4. Далее получим последние 30 строк логов системы:

```bash
golubgleb@Regius2:~$ dmesg | tail -n 30
[    9.465736] pci 2d52:00:00.0: BAR 4: assigned [mem 0xbffe16000-0xbffe16fff 64bit]
[    9.504317] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[    9.511024] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[    9.511776] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[    9.513174] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[    9.513812] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
[   25.078700] Exception:
[   25.078706] Operation canceled @p9io.cpp:258 (AcceptAsync)

[   47.204662] EXT4-fs (sdc): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered. Quota mode: none.
[   47.314883] FS-Cache: Duplicate cookie detected
[   47.315253] FS-Cache: O-cookie c=00000012 [p=00000002 fl=222 nc=0 na=1]
[   47.315545] FS-Cache: O-cookie d=000000007e70a936{9P.session} n=000000009d4a6071
[   47.315851] FS-Cache: O-key=[10] '34323934393432303139'
[   47.316025] FS-Cache: N-cookie c=00000013 [p=00000002 fl=2 nc=0 na=1]
[   47.316222] FS-Cache: N-cookie d=000000007e70a936{9P.session} n=00000000757db66d
[   47.316462] FS-Cache: N-key=[10] '34323934393432303139'
[   47.379601] FS-Cache: Duplicate cookie detected
[   47.379940] FS-Cache: O-cookie c=00000015 [p=00000002 fl=222 nc=0 na=1]
[   47.380249] FS-Cache: O-cookie d=000000007e70a936{9P.session} n=00000000254a026b
[   47.380575] FS-Cache: O-key=[10] '34323934393432303236'
[   47.380829] FS-Cache: N-cookie c=00000016 [p=00000002 fl=2 nc=0 na=1]
[   47.381130] FS-Cache: N-cookie d=000000007e70a936{9P.session} n=000000000f759827
[   47.381557] FS-Cache: N-key=[10] '34323934393432303236'
[   47.463496] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[   47.464091] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[   47.464781] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[   47.465191] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -22
[   47.465931] misc dxg: dxgk: dxgkio_query_adapter_info: Ioctl failed: -2
[   49.149285] hv_balloon: Max. dynamic memory size: 3994 MB
```

## Оценка результата

В результате лабораторной работы была получена базовая информация об используемой системе.

## Вывод

Таким образом. мы научились, используя команды Linux, получать сведения о системе.
